-- SQLite
CREATE TABLE TEAMS (
ID INT PRIMARY KEY NOT NULL,
NAME varchar(255) NOT NULL);

INSERT INTO TEAMS (ID, NAME) VALUES (1,"ATENEO");
INSERT INTO TEAMS (ID, NAME) VALUES (2,"AGLO");
INSERT INTO TEAMS (ID, NAME) VALUES (3,"THT");
INSERT INTO TEAMS (ID, NAME) VALUES (4,"AMERIKA");
INSERT INTO TEAMS (ID, NAME) VALUES (5,"PROYECTO BASQUET");
INSERT INTO TEAMS (ID, NAME) VALUES (6,"SHOLEM");
INSERT INTO TEAMS (ID, NAME) VALUES (7,"TRIGLAV");
INSERT INTO TEAMS (ID, NAME) VALUES (8,"SAHORES");
INSERT INTO TEAMS (ID, NAME) VALUES (9,"CABALLITO HEADS");
INSERT INTO TEAMS (ID, NAME) VALUES (10,"BETAM");

SELECT * FROM TEAMS;

CREATE TABLE PLAYERS (
ID INT PRIMARY KEY NOT NULL AUTOINCREMENT,
FIRST_NAME varchar(255) NOT NULL,
LAST_NAME varchar(255) NOT NULL,
AGE INT,
HEIGHT INT);

